# 사료작물의 분류 {#classification}

무질서 하게 보이는 자연현상을 실험과 관측을 통하여 어떤 규칙이나 질서를 밝혀냄으로서 인간의 일상생활을 보다 안정적이고 무지의 공포로부터 해방 시키는 것이 자연과학의 궁극적 목적인 것처럼 사료작물을 이해함에 있어 그 첫걸음은 인간이 이해하기 쉽게 질서정연하게 구분하고(분류) 이름짓는 일(명명)일 것이다.
그 첫번째 단계가 바로 여러사람이 쉽게 이해하고 수긍할 수 있는 기준과 방법에 의해 분류하는 것이다. 따라서 그 분류 방법과 기준은 사람에 따라, 지역에 따라 달라질 수도 있으며, 학문적 발달과 체계의 변화에 조금씩 변하기도 한다. 또 의해서 세계 모든 사람이 공통으로 사용할 수 있는 분류법도 있다.
목초나 사료잘물에 대한 분류는 사초생산계획 수립, 목적에 맞는 사초의 선택, 이용방법 등 사초를 이해하고 관리하는데 필수적이라 하겠다. 와 식별능력 없이는 식생의 지속적인 변화로 이루어지는 초지 생태계의 관리가 불가능하기 때문에 사초생산과 이용에 있어 중요한 의미를 갖는다.

## 생육적온에 의한 분류

식물을 생육가능한 온도의 범위와 가장 잘 자라는 온도(적온)에 따라 구분하면 식물은 생리적, 형태적, 세포학적으로 매우 다른 두 종류로 분류된다. 즉, 남방형(tropical grasses, warm-season grasses, 열대성 식물, 온지형 식물)과 북방형(temperate grasses, cool-season grasses, 한지형)으로 크게 나눌 수 있다.

## 형태에 의한 분류
**모든 분류 방법중 가장 널리 이용되는 분류방법이다.** 식물의 모양, 즉 인간이 눈으로 비교해 보고 식별이 가능한데서부터 출발하였다고 할 수 있다. 현재 이용되고 있는 사료작물은 그 형태에 따라 몇 종류만이 특히 농업적으로 중요하고 주로 이용되고 있기 때문에 이 분류방법이 쓰인다. 그러나 엄격히 말하면 정통 분류체계인 식물학적 분류방법도 이 방법에서 출발 하였다고 할 수 있다. 비록 편의에 의하여 축약하여 사용하여도 대부분의 사료작물이 이 범주에서 크게 벗어나지 않고, 간단명료한 장점이 있다. 특히 그 중에서도 두과와 화본과가 사료작물의 거의 대부분을 차지하기 때문에 이 두 종류가 주로 비교되기도 한다.

## 생존년한에 의한 분류

파종된 사료작물의 일생(life cycle)에 따라 구분. 일반밭작물 에서는 파종에서 수확까지 포장에서 유지되는 기간이, 목초에서는 지속성과 연관이 있으나 재배지역의 기후조건이나 재배관리 조건, 품종에 따라 달라지는 경우도 있다. 따라서 여기에 서술된 분류기준은 우리나라에서 재배되고 있는 일반적 초종을 기준으로 하고 있다.

2년생은 꼭 두 생육계절에 일생을 마친다기 보다 기후나, 품종, 관리방법에 따라 월년생이나 2~3년 동안 생육하는 경우도 있다. 또 1년생, 월년생, 2년생을 多年生 목초와 구분하기 위하여 단년생(單年生 ; short-lived grasses) 목초라고도 한다. 


## 이용형태에 의한 분류

사료작물을 이용형태에 따라 분류하면 청예작물(soiling crop, zero grazing, green chop), 다즙질 사초(succulent forage crop), 목초(pasture plants) 등으로 나눌 수 있다. 그러나 이 분류 방법은 낙농경영상 일반화 되어있기는 하나 같은 작물이라도 어떻게 이용하느냐에 따라 달라질 수 있기 때문에 적절한 분류방법이라고 볼 수 없다.

## 식물학적 분류

한 식물(생물)에 대한 이름은 국가마다, 언어에 따라, 심지어 한 국가 내에서도 지방에 따라 매우 달라서 식물을 이해하고 연구하는데 많은 어려움이 있다. 따라서 전 세계 모든 사람들이 공유할 수 있는 분류나 명명법의 필요성이 대두 되었고 국제회의에서 국제 명명 규약이 제정되어 체계적인 분류법이 과학의 발전과 더불어 학문의 한 분야로써 발전을 거듭하고 있다.

오늘날의 식물분류학은 식물의 꽃차례(花序)나 외부형태 뿐만아니라 세포학, 생화학, 생리학 등 모든 지식을 총동원 한 분류라고 할 수 있다.

### 식물학적 분류법의 특징

- 단 하나뿐인 유일한 이름이다.
- 전 세계 모든 사람들이 공통으로 사용한다.
- 학명은 모두 라틴어 또는 라틴어화한 단어를 사용한다.
- 이명법(二名法, binominal nomenclature; 모든 식물의 이름은 2개로 구성)을 사용한다
- 초종간의 상호관계와 식물의 특성을 짐작할 수 있다(종명은 속명을 수식하는 형용사)
- 바뀔 수 있다(식물 상호간의 관계에 대한 지식의 발전과 더불어 변화하고 있다)
- 屬 이상의 분류군 이름은 한 단어로된 일명법(一名法, uninomial)을 쓴다.